# Generated by Django 5.2 on 2025-05-07 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acrescimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrescimo_nome', models.CharField(max_length=100)),
                ('acrescimo_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acrescimo_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acréscimo',
                'verbose_name_plural': 'Acréscimos',
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento_nome', models.CharField(max_length=255)),
                ('estabelecimento_cnpj', models.CharField(max_length=14, unique=True)),
                ('estabelecimento_proprietario', models.CharField(max_length=255)),
                ('estabelecimento_telefone', models.CharField(max_length=20, unique=True)),
                ('estabelecimento_email', models.EmailField(max_length=254, unique=True)),
                ('estabelecimento_endereco', models.CharField(max_length=255)),
                ('estabelecimento_bairro', models.CharField(max_length=255)),
                ('estabelecimento_numero', models.CharField(max_length=10)),
                ('estabelecimento_complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('estabelecimento_cidade', models.CharField(max_length=100)),
                ('estabelecimento_estado', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_telefone', models.CharField(max_length=20, unique=True)),
                ('cliente_rua', models.CharField(max_length=255)),
                ('cliente_bairro', models.CharField(max_length=255)),
                ('cliente_numero', models.CharField(max_length=10)),
                ('cliente_complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='delivery.estabelecimento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='FormasDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento_nome', models.CharField(max_length=50)),
                ('forma_pagamento_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forma_pagamento', to='delivery.estabelecimento')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_data', models.DateTimeField(auto_now_add=True)),
                ('pedido_status', models.CharField(default='Pendente', max_length=50)),
                ('pedido_observacao', models.TextField(blank=True, null=True)),
                ('pedido_valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pedido_troco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.cliente')),
                ('pedido_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='delivery.estabelecimento')),
                ('pedido_forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.formasdepagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=255)),
                ('produto_descricao', models.TextField()),
                ('produto_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_imagem', models.ImageField(upload_to='delivery/imgs')),
                ('produto_ativo', models.BooleanField(default=True)),
                ('produto_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='delivery.estabelecimento')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='TamanhoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_produto_nome', models.CharField(max_length=50)),
                ('tamanho_produto_preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tamanho_produto_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanho_produto', to='delivery.estabelecimento')),
                ('tamanho_produto_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='delivery.produto')),
            ],
            options={
                'verbose_name': 'Tamanho de Produto',
                'verbose_name_plural': 'Tamanhos de Produto',
            },
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens_pedido_quantidade', models.PositiveIntegerField()),
                ('itens_pedido_preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itens_pedido_preco_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('itens_pedido_acrescimos', models.ManyToManyField(blank=True, to='delivery.acrescimo')),
                ('itens_pedido_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='delivery.estabelecimento')),
                ('itens_pedido_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='delivery.pedido')),
                ('itens_pedido_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.produto')),
                ('itens_pedido_tamanho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='delivery.tamanhoproduto')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Itens de Pedido',
            },
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produto_nome', models.CharField(max_length=50)),
                ('tipo_aceita_tamanho', models.BooleanField(default=False)),
                ('tipo_produto_ativo', models.BooleanField(default=True)),
                ('tipo_produto_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_produto', to='delivery.estabelecimento')),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'verbose_name_plural': 'Tipos de Produto',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='produto_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_produto', to='delivery.tipoproduto'),
        ),
        migrations.AddField(
            model_name='acrescimo',
            name='acrescimo_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_acrescimo', to='delivery.tipoproduto'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='delivery.estabelecimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cliente_estabelecimento'], name='delivery_cl_cliente_cf4f4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('cliente_estabelecimento', 'cliente_telefone')},
        ),
        migrations.AddIndex(
            model_name='tamanhoproduto',
            index=models.Index(fields=['tamanho_produto_produto'], name='delivery_ta_tamanho_0c68af_idx'),
        ),
        migrations.AddIndex(
            model_name='itenspedido',
            index=models.Index(fields=['itens_pedido_pedido'], name='delivery_it_itens_p_520bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='itenspedido',
            index=models.Index(fields=['itens_pedido_produto'], name='delivery_it_itens_p_888a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='itenspedido',
            index=models.Index(fields=['itens_pedido_tamanho'], name='delivery_it_itens_p_e8ee2d_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoproduto',
            index=models.Index(fields=['tipo_produto_estabelecimento'], name='delivery_ti_tipo_pr_fcb7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['produto_estabelecimento'], name='delivery_pr_produto_f17269_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['produto_tipo'], name='delivery_pr_produto_ea37aa_idx'),
        ),
        migrations.AddIndex(
            model_name='acrescimo',
            index=models.Index(fields=['acrescimo_tipo'], name='delivery_ac_acresci_3cd95d_idx'),
        ),
    ]
