# Generated by Django 5.2 on 2025-05-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanhoproduto',
            name='tamanho_produto_estabelecimento',
        ),
    ]
