# Generated by Django 5.2 on 2025-05-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_tamanhoproduto_tamanho_produto_estabelecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_url',
            field=models.SlugField(default='url-teste', max_length=255),
            preserve_default=False,
        ),
    ]
