# Generated by Django 5.2 on 2025-05-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_estabelecimento_estabelecimento_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='estabelecimento_url',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
