# Generated by Django 5.2 on 2025-05-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_estabelecimento_estabelecimento_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
