# Generated by Django 5.2 on 2025-05-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_cliente_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_logo',
            field=models.ImageField(default='pizzaria_logo.jpg', upload_to='delivery/imgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_prazo_entrega',
            field=models.IntegerField(default=0),
        ),
    ]
