# Generated by Django 5.2 on 2025-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_estabelecimento_estabelecimento_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_aberto',
            field=models.BooleanField(default=True),
        ),
    ]
