# Generated by Django 5.2 on 2025-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_estabelecimento_estabelecimento_aberto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
