# Generated by Django 5.2 on 2025-05-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_estabelecimento_estabelecimento_chave_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
