# Generated by Django 5.2 on 2025-05-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_produto_produto_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance', models.FloatField(verbose_name='Distância mínima (km)')),
                ('max_distance', models.FloatField(verbose_name='Distância máxima (km)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa de entrega (R$)')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_ranges', to='delivery.estabelecimento', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Faixa de entrega',
                'verbose_name_plural': 'Faixas de entrega',
                'ordering': ['min_distance'],
                'constraints': [models.UniqueConstraint(fields=('estabelecimento', 'min_distance', 'max_distance'), name='unique_delivery_range_per_estabelecimento')],
            },
        ),
    ]
