# Generated by Django 5.2 on 2025-05-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_deliveryrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_latitude',
            field=models.FloatField(default=-16.746979513250857),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_longitude',
            field=models.FloatField(default=-43.84287021821599),
            preserve_default=False,
        ),
    ]
