# Generated by Django 5.2 on 2025-06-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_estabelecimento_estabelecimento_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_taxa_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
