# Generated by Django 5.2 on 2025-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_cliente_cliente_taxa_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_tipo',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('retirada', 'Retirada')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('prepary', 'Em Preparo'), ('ready', 'Pronto'), ('delivery', 'Em Entrega'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
