# Generated by Django 5.2 on 2025-06-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_pedido_pedido_tipo_alter_pedido_pedido_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_tipo',
            new_name='pedido_tipo_entrega',
        ),
    ]
