# Generated by Django 5.2 on 2025-06-10 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_rename_pedido_tipo_pedido_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocao_nome', models.CharField(max_length=100)),
                ('promocao_descricao', models.TextField(blank=True, null=True)),
                ('promocao_preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('promocao_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promocao_ativo', models.BooleanField(default=True)),
                ('promocao_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoco7630es', to='delivery.estabelecimento')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
            },
        ),
        migrations.CreateModel(
            name='ItensPromocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_promocao', to='delivery.produto')),
                ('promocao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_fixos', to='delivery.promocao')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoItensPromocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_selecionavel', models.PositiveIntegerField(default=1)),
                ('itens', models.ManyToManyField(related_name='grupos_promocao', to='delivery.produto')),
                ('promocao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_itens', to='delivery.promocao')),
            ],
        ),
    ]
