# Generated by Django 5.2 on 2025-06-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_promocao_itenspromocao_grupoitenspromocao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='promocao_desconto',
        ),
        migrations.AddField(
            model_name='promocao',
            name='promocao_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/imgs'),
        ),
    ]
