# Generated by Django 5.2 on 2025-06-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_remove_promocao_promocao_desconto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_instagram',
            field=models.CharField(default='https://instagram.com', max_length=50),
            preserve_default=False,
        ),
    ]
